# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-sysele-nxp-6.6.52"
BBFILE_PATTERN_meta-sysele-nxp-6.6.52 = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-sysele-nxp-6.6.52 = "9"

LAYERDEPENDS_meta-sysele-nxp-6.6.52 = "core"
LAYERSERIES_COMPAT_meta-sysele-nxp-6.6.52 = "scarthgap"

#################################################################################################################
## Intel Realsense
PACKAGECONFIG:append:pn-librealsense2 = " rsusb"

## Enable SE05: comment it to use plug-and-trust-ecc and openssl-provider-se05 of meta-imx 
#ENABLE_SE05 = "1"

# ONSEMI
# Automatically build isp-vvcam (AF0130) with kernel
MACHINE_ESSENTIAL_EXTRA_RDEPENDS += "kernel-module-isp-vvcam \
                                     kernel-module-af0130 \
                                     kernel-module-imx8-media-dev"

# Optionally ensure it’s included in the rootfs
IMAGE_INSTALL:append = " kernel-module-isp-vvcam kernel-module-af0130 kernel-module-imx8-media-dev"

